version: "3"
services:
  php:
    image: php:fpm
    expose:
      - "9000"
    volumes:
      - "./webroot:/var/www/html"
    container_name: php

  nginx:
    image: nginx
    ports:
      - "127.0.0.1:85:80"
    volumes:
      - "./lidl.conf:/etc/nginx/conf.d/default.conf"
      - "./webroot:/var/www/html"
    container_name: nginx
    depends_on:
      - php

